<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nr_plugin_cache"
 *
 * Auto generated by Extension Builder 2014-01-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'TYPO3 cache test plugins',
    'description' => 'Test TYPO3 caching and locking',
    'category' => 'plugin',
    'author' => 'Christian Weiske',
    'author_email' => 'christian.weiske@netresearch.de',
    'author_company' => 'Netresearch GmbH&Co.KG',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '0.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.0.0-6.2.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);

?>